#!/usr/bin/env python3
"""
mermaid_draft.py - Draft and validate Mermaid diagrams for the
"Current vs Proposed" sections of each implementation phase.

This script does NOT generate finished diagrams. It produces a usable
*skeleton* per phase that the agent (or the user) refines. Skeletons are
deterministic given the workspace state, so they make a great starting
point and round-trip cleanly through re-renders.

Subcommands:

    draft  --workspace <ws> [--phase <N> ...] [--style flowchart|sequence]
           [--force]
        For each phase listed (default: all phases in
        manifest.phases), write workspace/diagrams/phase-<N>-<slug>.mmd
        from a template that:
        - Lists the user's repo-scan sources / investigation sources
          as participating nodes when present
        - Has a "Current" subgraph and a "Proposed" subgraph
        - Marks every node with a TODO comment so the user can swap in
          real names
        Updates manifest.steps.diagrams.draft.

    validate --workspace <ws> [--file <relative-path>]
        Lint every .mmd under workspace/diagrams/ (or just one file).
        Returns exit 3 if any file is malformed.

    list --workspace <ws>
        Print a compact JSON of the current diagrams folder.

    embed --workspace <ws> [--phase <N> ...] [--force] [--dry-run]
        Inline each phase's .mmd into the matching "Phase N:" block of
        workspace/sections/05-implementation-phases.md, wrapped in a
        ```mermaid fenced code block. Idempotent: re-runs replace the
        existing inline block in place. Requires section 05 to be
        present and to contain a "**Current vs. Proposed Flow**:"
        marker for each targeted phase. With --dry-run, print the
        intended changes without writing.

Output files:

    workspace/diagrams/diagrams.json    -- index of phase -> file
    workspace/diagrams/phase-<N>-<slug>.mmd

Manifest:

    steps.diagrams.draft = {
        "status": "in-progress" | "done" | "stale" | "skipped",
        "files": ["phase-1-foo.mmd", ...],
        "updatedAt": "..."
    }
"""
from __future__ import annotations
import argparse
import datetime
import json
import re
import sys
from pathlib import Path

VALID_HEADERS = (
    "flowchart", "graph", "sequenceDiagram", "classDiagram", "stateDiagram",
    "stateDiagram-v2", "erDiagram", "journey", "gantt", "pie", "mindmap",
    "timeline",
)


def now_iso() -> str:
    return datetime.datetime.utcnow().replace(microsecond=0).isoformat() + "Z"


def _read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def slugify(s: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "-", s.strip().lower()).strip("-")
    return s or "phase"


def _sanitize_id(name: str) -> str:
    """Mermaid node id: alnum + underscore."""
    ident = re.sub(r"[^A-Za-z0-9]+", "_", name.strip()).strip("_")
    if not ident:
        ident = "node"
    if ident[0].isdigit():
        ident = "n_" + ident
    return ident[:48]


FLOWCHART_TEMPLATE = """%% Phase {n}: {name}
%% Generated by dev-design mermaid_draft.py. Replace TODO labels with real names.
%% Round-trip safe: re-running --force will overwrite this file.

flowchart LR
    subgraph Current["Current state"]
{current_nodes}
{current_edges}
    end

    subgraph Proposed["Proposed state"]
{proposed_nodes}
{proposed_edges}
    end

{cross_edges}

    classDef todo stroke-dasharray: 4 4,stroke:#888,color:#666;
{todo_class}
"""

SEQUENCE_TEMPLATE = """%% Phase {n}: {name}
%% Generated by dev-design mermaid_draft.py. Replace TODO labels with real names.

sequenceDiagram
    autonumber
{participants}
{current_block}
    Note over {first_actor}: --- Proposed ---
{proposed_block}
"""


def _build_flowchart(n: int, name: str, sources: list[dict]) -> str:
    """Produce a flowchart skeleton seeded with the investigation/repo sources."""
    current_nodes_lines: list[str] = []
    proposed_nodes_lines: list[str] = []
    current_edges_lines: list[str] = []
    proposed_edges_lines: list[str] = []
    todo_lines: list[str] = []
    cross_edges_lines: list[str] = []

    if not sources:
        sources = [{"name": "Component A"}, {"name": "Component B"}]

    cur_ids: list[str] = []
    prop_ids: list[str] = []
    for s in sources:
        nm = s.get("name") or s.get("id") or "Component"
        ident = _sanitize_id(nm)
        cur_id = f"cur_{ident}"
        prop_id = f"prop_{ident}"
        cur_ids.append(cur_id)
        prop_ids.append(prop_id)
        current_nodes_lines.append(f"        {cur_id}[\"{nm} <!-- TODO: today's role -->\"]:::todo")
        proposed_nodes_lines.append(f"        {prop_id}[\"{nm} <!-- TODO: phase {n} role -->\"]:::todo")
        todo_lines.append(f"    class {cur_id},{prop_id} todo;")

    for a, b in zip(cur_ids, cur_ids[1:]):
        current_edges_lines.append(f"        {a} --> {b}")
    for a, b in zip(prop_ids, prop_ids[1:]):
        proposed_edges_lines.append(f"        {a} --> {b}")

    for cur_id, prop_id in zip(cur_ids, prop_ids):
        cross_edges_lines.append(
            f"    {cur_id} -.->|migration <!-- TODO -->| {prop_id}"
        )

    return FLOWCHART_TEMPLATE.format(
        n=n,
        name=name,
        current_nodes="\n".join(current_nodes_lines) or "        cur_todo[\"<!-- TODO -->\"]:::todo",
        current_edges="\n".join(current_edges_lines),
        proposed_nodes="\n".join(proposed_nodes_lines) or "        prop_todo[\"<!-- TODO -->\"]:::todo",
        proposed_edges="\n".join(proposed_edges_lines),
        cross_edges="\n".join(cross_edges_lines),
        todo_class="\n".join(todo_lines),
    )


def _build_sequence(n: int, name: str, sources: list[dict]) -> str:
    if not sources:
        sources = [{"name": "Client"}, {"name": "Service"}]
    participants = []
    actors = []
    for s in sources:
        nm = s.get("name") or s.get("id") or "Actor"
        ident = _sanitize_id(nm)
        participants.append(f"    participant {ident} as {nm}")
        actors.append(ident)
    first = actors[0]
    last = actors[-1]

    current_block = "\n".join([
        f"    {first}->>+{last}: existing call <!-- TODO -->",
        f"    {last}-->>-{first}: response <!-- TODO -->",
    ])
    proposed_block = "\n".join([
        f"    {first}->>+{last}: new call for phase {n} <!-- TODO -->",
        f"    {last}-->>-{first}: enriched response <!-- TODO -->",
    ])

    return SEQUENCE_TEMPLATE.format(
        n=n, name=name,
        participants="\n".join(participants),
        current_block=current_block,
        proposed_block=proposed_block,
        first_actor=first,
    )


def collect_sources(ws: Path, manifest: dict) -> list[dict]:
    """Pull a deduped list of participating components from repo-scan + investigation."""
    sources: list[dict] = []
    seen: set[str] = set()

    # Investigation synth/repos.json
    repos_path = ws / "workspace" / "investigation" / "synth" / "repos.json"
    if repos_path.exists():
        try:
            for r in _read_json(repos_path):
                nm = r.get("name") or r.get("id")
                if nm and nm.lower() not in seen:
                    sources.append({"name": nm, "id": r.get("id"), "origin": "investigation"})
                    seen.add(nm.lower())
        except Exception:
            pass

    # Repo scan: fall back to the workspace's own repo (if not already covered)
    scan_path = ws / "workspace" / "inputs" / "repo-scan.json"
    if not sources and scan_path.exists():
        try:
            scan = _read_json(scan_path)
            root = scan.get("root") or ""
            nm = Path(root).name if root else "Repo"
            if nm and nm.lower() not in seen:
                sources.append({"name": nm, "id": "repo", "origin": "repo-scan"})
                seen.add(nm.lower())
        except Exception:
            pass

    return sources


def cmd_draft(args, ws: Path, manifest_path: Path, manifest: dict) -> int:
    diagrams_dir = ws / "workspace" / "diagrams"
    diagrams_dir.mkdir(parents=True, exist_ok=True)

    step = manifest.setdefault("steps", {}).setdefault("diagrams.draft", {})
    if step.get("status") == "done" and not args.force and not args.phase:
        print(json.dumps({
            "skipped": True,
            "reason": "diagrams already drafted; pass --force or --phase <N> to refresh",
            "files": step.get("files", []),
        }))
        return 0

    phases = manifest.get("phases") or []
    if not phases:
        # Fall back to user-answered phases captured by the walker in answers.json.
        try:
            answers_path = ws / "workspace" / "inputs" / "answers.json"
            if answers_path.exists():
                ans = _read_json(answers_path)
                ans_phases = ans.get("phases") or []
                phases = [
                    {"name": p} if isinstance(p, str) else (p or {"name": "Phase"})
                    for p in ans_phases
                ]
        except Exception:
            phases = []
    if not phases:
        phases = [{"name": "Implementation"}]
    # Normalize phases to dicts with at least a name.
    phases = [
        {"name": p} if isinstance(p, str) else p
        for p in phases
    ]

    targets = args.phase or list(range(1, len(phases) + 1))
    sources = collect_sources(ws, manifest)
    written: list[str] = []
    for n in targets:
        if n < 1 or n > len(phases):
            print(json.dumps({"error": f"phase {n} not in manifest.phases (1..{len(phases)})"}), file=sys.stderr)
            return 3
        ph = phases[n - 1]
        name = ph.get("name") or f"Phase {n}"
        slug = slugify(name)
        fname = f"phase-{n}-{slug}.mmd"
        out = diagrams_dir / fname

        if out.exists() and not args.force:
            written.append(fname)
            continue
        if args.style == "sequence":
            body = _build_sequence(n, name, sources)
        else:
            body = _build_flowchart(n, name, sources)
        out.write_text(body, encoding="utf-8")
        written.append(fname)

    index = {
        "generatedAt": now_iso(),
        "style": args.style,
        "phases": [
            {"phase": n, "name": (phases[n - 1].get("name") if n <= len(phases) else f"Phase {n}"),
             "file": fname}
            for n, fname in zip(targets, written)
        ],
    }
    _write_json(diagrams_dir / "diagrams.json", index)

    incomplete = any(not (diagrams_dir / f"phase-{i+1}-{slugify(p.get('name') or f'Phase {i+1}')}.mmd").exists()
                     for i, p in enumerate(phases))
    step["status"] = "in-progress" if incomplete else "done"
    step["files"] = sorted({(diagrams_dir / f).name for f in written
                            if (diagrams_dir / f).exists()})
    step["updatedAt"] = now_iso()
    # Section render goes stale because phase 5 picks up the new diagram.
    sec = manifest.get("steps", {}).get("sections.render")
    if sec and sec.get("status") == "done":
        sec["status"] = "stale"
    asm = manifest.get("steps", {}).get("assemble")
    if asm and asm.get("status") == "done":
        asm["status"] = "stale"
    manifest["updatedAt"] = now_iso()
    _write_json(manifest_path, manifest)

    print(json.dumps({
        "ok": True,
        "draftedPhases": targets,
        "files": step["files"],
        "diagramsDir": str(diagrams_dir),
        "status": step["status"],
        "sourceCount": len(sources),
    }, indent=2))
    return 0


def validate_file(path: Path) -> list[str]:
    """Return list of problems; empty = valid."""
    problems: list[str] = []
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        return [f"read failed: {e}"]
    if not text.strip():
        return ["empty file"]
    # First non-comment, non-blank line must start with a known mermaid keyword.
    first_real = None
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("%%"):
            continue
        first_real = stripped
        break
    if not first_real:
        problems.append("no diagram body (only comments)")
    else:
        ok = any(first_real.split()[0] == h or first_real.startswith(h + " ")
                 for h in VALID_HEADERS)
        if not ok:
            problems.append(
                f"first non-comment line does not start with a known mermaid keyword: {first_real[:60]!r}"
            )
    # Balanced brackets across the file (rough check, ignoring inside ``).
    sanitized = re.sub(r"`[^`]*`", "", text)
    for open_c, close_c in (("[", "]"), ("(", ")"), ("{", "}")):
        diff = sanitized.count(open_c) - sanitized.count(close_c)
        if diff != 0:
            problems.append(f"unbalanced {open_c}{close_c}: open-close = {diff}")
    if "-->" not in sanitized and "->>" not in sanitized and "---" not in sanitized:
        problems.append("no edges / arrows detected; diagram may be empty")
    return problems


def cmd_validate(args, ws: Path, manifest_path: Path, manifest: dict) -> int:
    diagrams_dir = ws / "workspace" / "diagrams"
    if args.file:
        paths = [diagrams_dir / args.file] if not Path(args.file).is_absolute() else [Path(args.file)]
    else:
        if not diagrams_dir.exists():
            print(json.dumps({"ok": True, "files": [], "reason": "no diagrams folder yet"}))
            return 0
        paths = sorted(diagrams_dir.glob("*.mmd"))
    if not paths:
        print(json.dumps({"ok": True, "files": []}))
        return 0
    results: dict[str, list[str]] = {}
    for p in paths:
        results[p.name] = validate_file(p)
    bad = {k: v for k, v in results.items() if v}
    if bad:
        print(json.dumps({"ok": False, "problems": bad}, indent=2), file=sys.stderr)
        return 3
    print(json.dumps({"ok": True, "files": list(results.keys())}, indent=2))
    return 0


def cmd_list(args, ws: Path, manifest_path: Path, manifest: dict) -> int:
    diagrams_dir = ws / "workspace" / "diagrams"
    if not diagrams_dir.exists():
        print(json.dumps({"files": [], "indexExists": False}))
        return 0
    files = sorted(p.name for p in diagrams_dir.glob("*.mmd"))
    idx_path = diagrams_dir / "diagrams.json"
    index = _read_json(idx_path) if idx_path.exists() else None
    print(json.dumps({
        "files": files, "diagramsDir": str(diagrams_dir),
        "index": index, "indexExists": idx_path.exists(),
    }, indent=2))
    return 0


# ---------------------------------------------------------------------------
# embed: inline each phase's .mmd into sections/05-implementation-phases.md
# ---------------------------------------------------------------------------

# Match: "**Current vs. Proposed Flow**:" line, optional blank line(s), then
# either (a) an existing ```mermaid ... ``` block (we replace it in place),
# (b) a "See `workspace/diagrams/...`" reference line (we replace it), or
# (c) nothing yet (we insert after the marker).
FLOW_MARKER_RE = re.compile(
    r"(\*\*Current vs\.? Proposed Flow\*\*:[ \t]*)"
    r"(?P<existing>"
    r"[ \t]*See[^\n]*?\.mmd[^\n]*\n"
    r"|\n+```mermaid\n.*?\n```"
    r")?",
    re.DOTALL,
)

PHASE_HEADER_RE = re.compile(r"^### Phase (\d+):", re.MULTILINE)


def _phase_blocks(text: str) -> list[tuple[int, int, int]]:
    """Return [(phase_num, start_offset, end_offset), ...] for each Phase
    header in section 05. end_offset is the start of the next phase or EOF."""
    headers = list(PHASE_HEADER_RE.finditer(text))
    out = []
    for i, m in enumerate(headers):
        n = int(m.group(1))
        start = m.start()
        end = headers[i + 1].start() if i + 1 < len(headers) else len(text)
        out.append((n, start, end))
    return out


def _embed_in_phase(block_text: str, mermaid_body: str) -> tuple[str, str]:
    """Return (new_block_text, status) where status is 'inserted', 'replaced',
    or 'no-marker'. mermaid_body is the .mmd contents (no fences)."""
    body = mermaid_body.strip("\n")
    fenced = f"```mermaid\n{body}\n```"

    m = FLOW_MARKER_RE.search(block_text)
    if not m:
        return block_text, "no-marker"

    existing = m.group("existing")
    if existing and existing.lstrip().startswith("```mermaid"):
        # Replace in place (preserve the marker line; replace just the fenced block).
        new = block_text[:m.start("existing")] + "\n\n" + fenced + block_text[m.end("existing"):]
        if new == block_text:
            return block_text, "unchanged"
        return new, "replaced"

    if existing and existing.lstrip().startswith("See"):
        # Replace the inline "See ..." reference. The capture group includes
        # leading spaces and the trailing newline.
        new = block_text[:m.start("existing")] + "\n\n" + fenced + "\n" + block_text[m.end("existing"):]
        return new, "replaced"

    # No existing block — insert after the marker line.
    insertion_point = m.end(1)  # right after "**Current vs. Proposed Flow**:"
    new = block_text[:insertion_point] + "\n\n" + fenced + "\n" + block_text[insertion_point:]
    return new, "inserted"


def cmd_embed(args, ws: Path, manifest_path: Path, manifest: dict) -> int:
    section_path = ws / "workspace" / "sections" / "05-implementation-phases.md"
    if not section_path.exists():
        print(json.dumps({
            "error": "section 05-implementation-phases.md not found; "
                     "run the walker to create it first",
            "path": str(section_path),
        }), file=sys.stderr)
        return 3

    diagrams_dir = ws / "workspace" / "diagrams"
    if not diagrams_dir.exists():
        print(json.dumps({
            "error": "workspace/diagrams/ does not exist; run "
                     "'mermaid_draft.py draft' first",
        }), file=sys.stderr)
        return 3

    # Resolve phase -> .mmd path via diagrams.json when available, else
    # by globbing phase-<N>-*.mmd.
    idx_path = diagrams_dir / "diagrams.json"
    phase_to_file: dict[int, Path] = {}
    if idx_path.exists():
        try:
            idx = _read_json(idx_path)
            entries = idx.get("phases") or []
            for e in entries:
                n = int(e.get("phase"))
                fname = e.get("file")
                if fname:
                    p = diagrams_dir / fname
                    if p.exists():
                        phase_to_file[n] = p
        except Exception:
            pass
    # Fallback / supplement: glob
    for p in diagrams_dir.glob("phase-*.mmd"):
        m = re.match(r"phase-(\d+)-", p.name)
        if not m:
            continue
        n = int(m.group(1))
        phase_to_file.setdefault(n, p)

    if not phase_to_file:
        print(json.dumps({
            "error": "no phase-<N>-*.mmd files found under workspace/diagrams/",
        }), file=sys.stderr)
        return 3

    targets = args.phase or sorted(phase_to_file.keys())
    text = section_path.read_text(encoding="utf-8")
    blocks = _phase_blocks(text)
    if not blocks:
        print(json.dumps({
            "error": "section 05 has no '### Phase N:' headers; "
                     "fill the section before embedding diagrams",
        }), file=sys.stderr)
        return 3

    # Build a map of phase_num -> (start, end) for fast lookup.
    by_phase: dict[int, tuple[int, int]] = {n: (s, e) for n, s, e in blocks}

    results = []
    new_text = text
    # Apply replacements right-to-left so offsets remain valid.
    for n in sorted(targets, reverse=True):
        if n not in phase_to_file:
            results.append({"phase": n, "status": "no-mmd-file"})
            continue
        if n not in by_phase:
            results.append({"phase": n, "status": "no-phase-header"})
            continue
        start, end = by_phase[n]
        block = new_text[start:end]
        mermaid_body = phase_to_file[n].read_text(encoding="utf-8")
        updated, status = _embed_in_phase(block, mermaid_body)
        if not args.force and status == "unchanged":
            results.append({"phase": n, "status": "unchanged", "file": phase_to_file[n].name})
            continue
        if status == "no-marker":
            results.append({"phase": n, "status": "no-marker", "file": phase_to_file[n].name})
            continue
        new_text = new_text[:start] + updated + new_text[end:]
        results.append({"phase": n, "status": status, "file": phase_to_file[n].name})

    # Reverse so output is phase-ascending.
    results.reverse()

    if args.dry_run:
        print(json.dumps({"dryRun": True, "results": results,
                          "changed": new_text != text}, indent=2))
        return 0

    if new_text != text:
        section_path.write_text(new_text, encoding="utf-8")
        # Mark assemble stale so the next render picks up the inlined diagrams.
        asm = manifest.get("steps", {}).get("assemble")
        if asm and asm.get("status") == "done":
            asm["status"] = "stale"
            manifest["updatedAt"] = now_iso()
            _write_json(manifest_path, manifest)

    print(json.dumps({
        "ok": True,
        "results": results,
        "sectionPath": str(section_path),
        "changed": new_text != text,
    }, indent=2))
    return 0



def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    p_d = sub.add_parser("draft", help="Draft mermaid skeletons per phase.")
    p_d.add_argument("--workspace", required=True)
    p_d.add_argument("--phase", type=int, action="append",
                     help="Phase number to draft (1-based). Repeatable. Default: all phases.")
    p_d.add_argument("--style", choices=["flowchart", "sequence"], default="flowchart")
    p_d.add_argument("--force", action="store_true")

    p_v = sub.add_parser("validate", help="Validate mermaid files.")
    p_v.add_argument("--workspace", required=True)
    p_v.add_argument("--file", default="",
                     help="Single file to validate (path relative to diagrams dir).")

    p_l = sub.add_parser("list", help="List drafted mermaid files.")
    p_l.add_argument("--workspace", required=True)

    p_e = sub.add_parser("embed", help="Inline each phase's .mmd into section 05.")
    p_e.add_argument("--workspace", required=True)
    p_e.add_argument("--phase", type=int, action="append",
                     help="Phase number to embed (1-based). Repeatable. Default: all phases with a .mmd file.")
    p_e.add_argument("--force", action="store_true",
                     help="Re-write the inlined block even if it already matches the .mmd.")
    p_e.add_argument("--dry-run", action="store_true",
                     help="Print the intended changes without writing.")

    args = p.parse_args()
    ws = Path(args.workspace).resolve()
    manifest_path = ws / "workspace" / "manifest.json"
    if not manifest_path.exists():
        print(json.dumps({"error": f"manifest not found at {manifest_path}"}), file=sys.stderr)
        return 2
    manifest = _read_json(manifest_path)

    if args.cmd == "draft":
        return cmd_draft(args, ws, manifest_path, manifest)
    if args.cmd == "validate":
        return cmd_validate(args, ws, manifest_path, manifest)
    if args.cmd == "list":
        return cmd_list(args, ws, manifest_path, manifest)
    if args.cmd == "embed":
        return cmd_embed(args, ws, manifest_path, manifest)
    return 2


if __name__ == "__main__":
    sys.exit(main())
